
platform :ios, '10.0'
#     use_frameworkds!

target 'SeniorProject' do
use_frameworks!

#pod 'Alamofire', '~> 5.0.0-beta.2'
pod 'SVProgressHUD'
pod 'Alamofire'
pod 'Parse'
pod 'Parse/UI'
pod "BCryptSwift"



end
